version: "3"
services:
    web:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/html
            - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
            - ../logs/nginx/:/var/log/nginx
        links:
            - php
            - db

    php:
        build:
            context: php
            args:
                TIMEZONE: ${TIMEZONE}
                UID: ${UID}

        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/html
            - ../logs/symfony/:/var/www/html/var/log
        links:
            - db
        env_file:
            - ${SYMFONY_APP_PATH}/.env

    db:
        image: mysql:5
        volumes:
            - ../mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8082:80
        links:
            - db
        volumes:
            - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

